[package]
name = "mimium-audio-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arboard = "3"
base64 = "0.22"
clack-plugin = { git = "https://github.com/prokopyl/clack.git", rev = "4541f03792635dfdc6be9441a01b786e9b4ccf18" }
clack-extensions = { git = "https://github.com/prokopyl/clack.git", rev = "4541f03792635dfdc6be9441a01b786e9b4ccf18", features = ["audio-ports", "clack-plugin", "gui", "params", "state", "timer"] }
include_dir = "0.7"
libc = "0.2"
mimium-lang = "4.1.1"
mimium-plugin-macros = "4.1.1"
raw-window-handle = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
wry = { git = "https://github.com/tomoyanonymous/wry.git", rev = "c94c79dc4502d02a964f370f7babcdcb25547485" }
